input_pdf: ./data/sample.pdf
input_dir: ./data/
batch_mode: true
output_csv: true
ticket_numbers_csv: true
page_fields_csv: true
ticket_number_exceptions_csv: true
manifest_number_exceptions_csv: true
summary_report: true
draw_roi: true
orientation_check: tesseract  # tesseract, doctr, or none
pdf_scale: 1.0  # scale vendor PDFs (1.0 = original size)
pdf_resolution: 150
save_corrected_pdf: true
corrected_pdf_path: ./outputs/corrected.pdf
parallel: true
num_workers: 4
debug: false
profile: false

# OCR Engine Configuration
ocr_engine: tesseract  # tesseract, easyocr, or doctr

# OCR Engine Parameters (engine-specific)
ocr_engine_params:
  tesseract:
    lang: eng
    config: "--psm 6"
    timeout: 30
  easyocr:
    languages: ["en"]
    gpu: false
  doctr:
    pretrained: true
    det_arch: "db_resnet50" 
    reco_arch: "crnn_vgg16_bn"
    assume_straight_pages: true

# OCR Caching Configuration
ocr_cache:
  enabled: true
  cache_dir: ./outputs/ocr_cache

preflight:
  enabled: false

