batch_mode: false            # true = process input_dir, false = just input_pdf
input_pdf:
input_dir:

# Combined OCR dump (page-level)
output_csv: ./output/logs/ocr/combined_results.csv

# Deduped ticket numbers
ticket_numbers_csv: ./output/ticket_number/combined_ticket_numbers.csv
page_fields_csv: ./output/ticket_number/page_fields.csv

# Pages that had *no* ticket numbers
ticket_number_exceptions_csv: ./output/logs/ticket_number/ticket_number_exceptions.csv
manifest_number_exceptions_csv: ./output/logs/manifest_number/manifest_number_exceptions.csv

# Summary stats
summary_report_dir: ./output/logs/summary  # directory only, not the full filename

vendor_keywords_csv: ./ocr_keywords.csv
extraction_rules_yaml: ./extraction_rules.yaml
poppler_path: C:/Poppler/poppler-24.08.0/Library/bin      # Poppler path for Windows/PDF2Image

orientation_check: tesseract            # tesseract, doctr, or none
parallel: true                            # USE parallel processing!
num_workers: 16                           # Start with 8, can go higher if you want
identifier: ""                            # Optional: set if you want
profile: true                             # Get timing info, helpful for tuning

save_images: false                         # Only if you want images, else keep false for speed
output_images_dir: ./output/images
draw_roi: true                           # Only true if you want ROI images
draw_ocr_boxes: true                     # Only true if you want annotated OCR boxes
save_corrected_pdf: false            # Set to true if you want to save corrected PDF with rotated pages
corrected_pdf_path: ./output/final_pdf/corrected_pages.pdf                   # or another file name
debug: false  # or true

preflight:
  enabled: false  # Set to true to enable preflight checks
  dpi_threshold: 150

# Directory for dumping bad preflight PDFs (e.g., blank or unreadable pages)
exceptions_dir: ./output/exceptions/pdf

# Directory for saving single-page PNGs of failed OCR pages
runtime_error_images: ./output/exceptions/images

# Directory for timestamped merged exception CSVs
exceptions_csv_dir: ./output/exceptions/logs
