batch_mode: false
combined_pdf: false
csv_filename: results.csv
extraction_rules_yaml: ./extraction_rules.yaml
input_pdf: C:/Users/brian.atkins/OneDrive - Lindamood Demolition/24-105 PHMS NPC -
  Documents/truck tickets/2025-07-08/export/24-105_2025-07-08_class2_beck_WM_46.pdf
ocr_engine: doctr
orientation_check: tesseract
output_dir: ./outputs
output_format:
- csv
- excel
- vendor_pdf
pdf_resolution: 150
pdf_scale: 1.0
poppler_path: C:/Poppler/poppler-24.08.0/Library/bin
profile: false
sharepoint_config:
  credentials:
    password: password
    username: user@company.com
  folder: Tickets2025
  library: Documents
  site_url: https://company.sharepoint.com/sites/TruckTickets
vendor_keywords_csv: ./ocr_keywords.csv
