input_pdf: ./data/sample.pdf
input_dir: ./data/
batch_mode: true
output_csv: ./output/ocr/all_results.csv
ticket_numbers_csv: ./output/ocr/combined_ticket_numbers.csv
page_fields_csv: ./output/ocr/page_fields.csv
manifest_number_exceptions_csv: ./output/logs/manifest_number/manifest_number_exceptions.csv
output_images_dir: ./output/images/
draw_roi: true
orientation_check: tesseract  # tesseract, doctr, or none
save_corrected_pdf: true
corrected_pdf_path: ./output/ocr/corrected.pdf
parallel: true
num_workers: 4
debug: false
profile: false
