input_pdf: ./data/sample.pdf
input_dir: ./data/
batch_mode: true
output_csv: true
ticket_numbers_csv: true
page_fields_csv: true
ticket_number_exceptions_csv: true
manifest_number_exceptions_csv: true
summary_report: true
output_images_dir: ./output/images/
draw_roi: true
orientation_check: tesseract  # tesseract, doctr, or none
pdf_scale: 1.0  # scale vendor PDFs (1.0 = original size)
pdf_resolution: 150
save_corrected_pdf: true
corrected_pdf_path: ./output/ocr/corrected.pdf
parallel: true
num_workers: 4
debug: false
profile: false
