batch_mode: false
combined_pdf: true
corrected_pdf_path: ./output/ocr/corrected.pdf
csv_filename: results.csv
debug: false
draw_roi: true
extraction_rules_yaml: ./extraction_rules.yaml
hash_db_csv: ./outputs/hash_db.csv
input_pdf: C:/Users/brian.atkins/OneDrive - Lindamood Demolition/24-105 PHMS NPC -
  Documents/truck tickets/2025-08-05/export/24-105_2025-08-05_class2_beck_WM_25.pdf
log_csv: true
log_html: true
manifest_number_exceptions_csv: true
num_workers: 4
ocr_engine: doctr
orientation_check: tesseract
output_csv: true
output_dir: C:/Users/brian.atkins/OneDrive - Lindamood Demolition/24-105 PHMS NPC
  - Documents/truck tickets/2025-08-05/processed3
output_format:
- csv
- excel
- vendor_pdf
page_fields_csv: true
parallel: true
pdf_resolution: 150
pdf_scale: 1.0
poppler_path: C:/Poppler/poppler-24.08.0/Library/bin
preflight:
  blank_std_threshold: 3.0
  dpi_threshold: 150
  enabled: false
  min_chars: 5
  min_resolution: 600
preflight_exceptions_csv: ./output/logs/preflight/preflight_exceptions.csv
profile: false
run_type: initial
save_corrected_pdf: true
sharepoint_config:
  credentials:
    password: password
    username: user@company.com
  folder: Tickets2025
  library: Documents
  site_url: https://company.sharepoint.com/sites/TruckTickets
summary_report: true
ticket_number_exceptions_csv: true
ticket_numbers_condensed_csv: true
ticket_numbers_csv: true
validation_output_csv: ./outputs/validation_mismatches.csv
vendor_keywords_csv: ./ocr_keywords.csv
