"""Sphinx configuration for DocTR Process API documentation."""

import os
import sys
from datetime import datetime

# Add the source directory to the path
sys.path.insert(0, os.path.abspath("../../src"))

# Project information
project = "DocTR Process"
copyright = f"{datetime.now().year}, DocTR Process Team"  # noqa: DTZ005, A001
author = "DocTR Process Team"
version = "1.0.0"
release = "1.0.0"

# Extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",  # Google/NumPy style docstrings
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# Autosummary settings
autosummary_generate = True
autosummary_imported_members = True

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/20/", None),
}

# HTML output settings
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_css_files = ["custom.css"]

# Show source links
html_show_sourcelink = True

# Add any paths that contain templates here
templates_path = ["_templates"]

# The suffix(es) of source filenames
source_suffix = ".rst"

# The master toctree document
master_doc = "index"

# General information about the project
project = "DocTR Process"

# The version info for the project
version = "1.0.0"
release = "1.0.0"

# The language for content autogenerated by Sphinx
language = "en"

# Output file base name
html_title = f"DocTR Process API Documentation v{version}"
html_short_title = "DocTR Process API"

# Logo
html_logo = None

# Favicon
html_favicon = None

# Show the "Created using Sphinx" credit in the footer
html_show_sphinx = True

# Show the copyright in the footer
html_show_copyright = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sourcelink = True

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.
html_use_opensearch = ""

# This is the file name suffix for HTML files
html_file_suffix = ".html"

# Language to be used for generating the HTML full-text search index.
html_search_language = "en"

# A dictionary with options for the full-text search
html_search_options = {"type": "default"}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
html_search_scorer = ""

# Output file base name for HTML help builder
htmlhelp_basename = "DocTRProcessDoc"

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author,
#  dirmenu entry, description, category)
latex_documents = [
    (
        master_doc,
        "DocTRProcess.tex",
        "DocTR Process API Documentation",
        "DocTR Process Team",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_toplevel_sectioning = "part"

# If true, show page references after internal links.
latex_show_pagerefs = False

# If true, show URL addresses after external links.
latex_show_urls = False

# Documents to append as an appendix to all manuals.
latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True

# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section)
man_pages = [
    (master_doc, "doctrprocess", "DocTR Process API Documentation", [author], 1)
]

# If true, show URL addresses after external links.
man_show_urls = False

# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "DocTRProcess",
        "DocTR Process API Documentation",
        author,
        "DocTRProcess",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = "footnote"

# If true, do not generate a @detailmenu in the "Top" node's menu.
texinfo_no_detailmenu = False
